# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build-base: &build-base
    working_directory: ~/repo

  build-node-v8:
    <<: *build-base
    docker:
      # specify the version you desire here
      - image: circleci/node:8@sha256:bba459fbda15808483daa60bfebff8ec5406ae9bfe5608bff5c72f65c3a6e1e5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v8-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v8-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn test -w 1

  build-node-v10:
    <<: *build-base
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v10-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v10-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v10-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn test -w 1

workflows:
  version: 2
  node-multi-build:
    jobs:
      - build-node-v8
      - build-node-v10
